-- 使用するDBを作成するクエリを記述したファイルです

-- HimyDBを作成します。
CREATE DATABASE IF NOT EXISTS HimyDB DEFAULT CHARACTER SET=UTF8;
GRANT ALL PRIVILEGES ON HimyDB .* TO 'HimyApp'@localhost IDENTIFIED BY '+2QwJpBh';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON HimyDB .* TO 'HimyApp'@'%' IDENTIFIED BY '+2QwJpBh';
FLUSH PRIVILEGES;

-- HimyTestDBを作成します。
CREATE DATABASE IF NOT EXISTS HimyTestDB DEFAULT CHARACTER SET=UTF8;
GRANT ALL PRIVILEGES ON HimyTestDB .* TO 'HimyApp'@localhost IDENTIFIED BY '+2QwJpBh';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON HimyTestDB .* TO 'HimyApp'@'%' IDENTIFIED BY '+2QwJpBh';
FLUSH PRIVILEGES;
